### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by ghost** [swooningfish/ffmpeg-web-gui#1]
Love the idea and would like a little more information. I was wondering if you could add some information on how to install this on a windows server please?

It looks like ffmpeg has to be installed on the server. If I do that, how do I modify or what do I have to modify to run the upload and convert to point to the correct directory?

Any documentation or help would be greatly appreciated.

**Comment by swooningfish** [comment]
FFmpeg docs can be found here https://ffmpeg.org/documentation.html You can download the source and compile, or download a windows binary for your system.
