### ISSUE TITLE
X265/HEVC Output

### ISSUE THREAD

**Issue by parth-khant** [swooningfish/ffmpeg-web-gui#3]
Can you please add x265 as output

**Comment by swooningfish** [comment]
Hi @InnovaHacker 

Sorry not really supporting this, but it looks like you should be able to use the x265 with this command `ffmpeg -i input -c:v libx265 -crf 28 -c:a aac -b:a 128k output.mp4` source https://trac.ffmpeg.org/wiki/Encode/H.265

Adding a new condition for `if (isset($_POST['encoding_x264'])) {` to `if (isset($_POST['encoding_x265'])) {` etc.. but i guessit would also need different constant rate factors (CRF) as another param unless this is it's hardcoded at 28.

Happy to accept pull requests :)
